import pyautogui as pag
from set_button_and_game import *
def firstinningUP():
    # 1 бьющий
    kstrike()
    ball()
    outon1base()
    pag.leftClick(x2BTN[1], y2BTN, duration=d)
    pag.leftClick(xnumbers[7], ynumbers, duration=d)
    done()

    # # 2 бьющий
    ball()
    ball()
    kstrike()
    ball()
    ball()

    # # 3 бьющий (удар с первого, однобазовый хит с продвижением до 2 по ошибке 7)
    twobasehit()
    pag.leftClick(x2BTN[0], y2BTN, duration=d)
    pag.leftClick(xnumbers[6], ynumbers, duration=d)
    pag.leftClick(x3BTN[1], y3BTN, duration=d)
    pag.leftClick(x4BTN[3], y4BTN, duration=d)
    done()
    done()
    # 4 бьющий
    onebasehit()
    pag.leftClick(x2BTN[0], y2BTN, duration=d)
    pag.leftClick(xnumbers[3], ynumbers, duration=d)
    done()
    done()
    # # 5 
    kstrike()
    ball()
    ball()
    ball()
    foul()
    ball()
    done()
    # # 6
    kstrike()
    swing()
    swing()
    done()
    # 7 
    ball()
    foul()
    onebasehit()
    pag.leftClick(x2BTN[0], y2BTN, duration=d)
    pag.leftClick(xnumbers[7], ynumbers, duration=d)
    done()
    done()
    # 8 (аут бегуну в дом)
    onebasehit()
    pag.mouseDown(xBASE[3],yBASE[3], button='left')
    pag.moveTo(xOUT[3], yOUT[3], d)
    pag.mouseUp()
    pag.leftClick(xnumbers[0],ynumbers,duration=d)
    pag.leftClick(xnumbers[1],ynumbers, duration=d)
    done()
    pag.leftClick(x2BTN[0], y2BTN, duration=d)
    done()
    pag.leftClick(x2BTN[0], y2BTN, duration=d)
    done()
    pag.leftClick(x2BTN[0], y2BTN, duration=d)
    done()
    done()  
